{{- if and .Values.metadataDatabase.enabled .Values.metadataDatabase.password }}
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-metadata-database
    namespace: {{ .Release.Namespace }}
type: Opaque
data:
    password: {{ .Values.metadataDatabase.password | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-object-storage
    namespace: {{ .Release.Namespace }}
type: Opaque
data:
    connection: {{ include "gitlab.objectstorage" . | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-registry-storage
    namespace: {{ .Release.Namespace }}
type: Opaque
data:
    config: {{ include "gitlab.registrystorage" . | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-s3cmd-config
    namespace: {{ .Release.Namespace }}
type: Opaque
data:
    config: {{ include "gitlab.s3cmdconfig" . | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-smtp-password
    namespace: {{ .Release.Namespace }}
type: Opaque
data:
    password: {{ .Values.smtp.password | b64enc }}