---
{{- if .Values.metricsIngress.host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metrics
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.metricsIngress.tlsIssuer | default "letsencrypt-staging" | quote }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.metricsIngress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ coalesce .Values.metrics.fullnameOverride .Values.metrics.nameOverride "metrics" }}
                port:
                  number: 8080
  tls:
    - hosts:
      - {{ .Values.metricsIngress.host }}
      secretName: metrics-tls
{{- end}}