apiVersion: apps/v1
metadata:
  labels:
    control-plane: controller-manager
  name: gitlab-controller-manager
  namespace: {{ .Release.Namespace }}
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      nodeSelector:
        node-role.kubernetes.io/gitlab: "true"
      containers:
      - args:
        - --metrics-addr=:8443
        - --enable-leader-election
        - --zap-devel=false
        - --zap-log-level=info
        - --zap-time-encoding=epoch
        command:
        - /manager
        image: registry.gitlab.com/gitlab-org/cloud-native/gitlab-operator:2.1.2
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 6060
          name: health-port
        - containerPort: 8443
          name: metrics
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GITLAB_MANAGER_SERVICE_ACCOUNT
          value: gitlab-manager
        - name: GITLAB_APP_NONROOT_SERVICE_ACCOUNT
          value: gitlab-app-nonroot
        - name: NGINX_SERVICE_ACCOUNT
          value: gitlab-nginx-ingress
        - name: PROMETHEUS_SERVICE_ACCOUNT
          value: gitlab-prometheus-server
        livenessProbe:
          httpGet:
            path: /liveness
            port: health-port
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readiness
            port: health-port
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 200m
            memory: 100Mi
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      serviceAccountName: gitlab-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
