apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
kind: RoleBinding
subjects:
- kind: ServiceAccount
  name: gitlab-manager
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-leader-election-role
---
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-nginx-ingress
  namespace: {{ .Release.Namespace }}
kind: RoleBinding
subjects:
- kind: ServiceAccount
  name: gitlab-nginx-ingress
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-nginx-ingress
