apiVersion: v1
metadata:
  name: gitlab-app-nonroot
  namespace: {{ .Release.Namespace }}
  annotations: {}
kind: ServiceAccount
---
apiVersion: v1
metadata:
  name: gitlab-manager
  namespace: {{ .Release.Namespace }}
kind: ServiceAccount
---
apiVersion: v1
metadata:
  name: gitlab-nginx-ingress
  namespace: {{ .Release.Namespace }}
kind: ServiceAccount
---
apiVersion: v1
metadata:
  name: gitlab-prometheus-server
  namespace: {{ .Release.Namespace }}
kind: ServiceAccount
