apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/instance: minio-operator
    name: minio-operator
    {{ include "minio.labels" . | nindent 4 }}
  name: operator
  namespace: {{ .Release.Namespace }}
  annotations:
    operator.min.io/authors: MinIO, Inc.
    operator.min.io/license: AGPLv3
    operator.min.io/support: https://subnet.min.io
kind: Service
spec:
  ports:
  - name: http
    port: 4221
  selector:
    name: minio-operator
    operator: leader
  type: ClusterIP
---
apiVersion: v1
metadata:
  labels:
    name: minio-operator
    {{ include "minio.labels" . | nindent 4 }}
  name: sts
  namespace: {{ .Release.Namespace }}
  annotations:
    operator.min.io/authors: MinIO, Inc.
    operator.min.io/license: AGPLv3
    operator.min.io/support: https://subnet.min.io
kind: Service
spec:
  ports:
  - name: https
    port: 4223
    targetPort: 4223
  selector:
    name: minio-operator
  type: ClusterIP
