apiVersion: v1
metadata:
  name: minio-operator
  namespace: {{ .Release.Namespace }}
  annotations:
    operator.min.io/authors: MinIO, Inc.
    operator.min.io/license: AGPLv3
    operator.min.io/support: https://subnet.min.io
  labels: {{ include "minio.labels" . | nindent 4 }}
kind: ServiceAccount
