apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
  namespace: {{ .Release.Namespace }}
stringData:
  config.env: |-
    export MINIO_ROOT_USER="{{ .Values.root.user }}"
    export MINIO_ROOT_PASSWORD="{{ .Values.root.password }}"
    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER="on"
type: Opaque
---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: {{ .Values.console.user | b64enc }}
  CONSOLE_SECRET_KEY: {{ .Values.console.password | b64enc }}
kind: Secret
metadata:
  name: storage-user
  namespace: {{ .Release.Namespace }}
type: Opaque
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  annotations:
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
  labels:
    app: minio
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  certConfig: {}
  configuration:
    name: storage-configuration
  env: []
  externalCaCertSecret: []
  externalCertSecret: []
  externalClientCertSecrets: []
  features:
    bucketDNS: false
    domains: {}
  image: quay.io/minio/minio:RELEASE.2025-06-13T11-33-47Z
  imagePullSecret: {}
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
    {{- range .Values.pools }}
    - affinity:
        nodeAffinity: {}
        podAffinity: {}
        podAntiAffinity: {}
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      name: {{ .name }}
      nodeSelector:
        node-role.kubernetes.io/minio: "true"
      resources: {}
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      servers: 4
      tolerations: []
      topologySpreadConstraints: []
      volumeClaimTemplate:
        apiVersion: v1
        kind: persistentvolumeclaims
        metadata: {}
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .size }}
          storageClassName: {{ .storageClassName }}
        status: {}
      volumesPerServer: 4
    {{- end}}
  priorityClassName: ""
  requestAutoCert: false
  serviceAccountName: ""
  serviceMetadata:
    consoleServiceAnnotations: {}
    consoleServiceLabels: {}
    minioServiceAnnotations: {}
    minioServiceLabels: {}
  subPath: ""
  users:
    - name: storage-user
